# -*- coding: utf-8 -*-
"""HackOWeek Task 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQmp1IL6RNsfp-EN5LyV6AVRmWPhJ6tr
"""

!pip install pandas numpy matplotlib scikit-learn plotly

from google.colab import files
uploaded = files.upload()

import zipfile

zip_path = "PublicationofBuildingEnergyPerformanceData.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("energy_data")

print("Files extracted successfully")

import pandas as pd

df = pd.read_csv("energy_data/Listing of Building Energy Performance Data for Commercial Buildings.csv")

df.head()

df = df.rename(columns={
    "2017energyuseintensity": "energy_intensity"
})

df = df.dropna(subset=["energy_intensity"])

df.head()

campus_energy = df.groupby("buildingtype")["energy_intensity"].mean().reset_index()

campus_energy.head()

import numpy as np
from sklearn.linear_model import LinearRegression

campus_energy["index"] = np.arange(len(campus_energy))

X = campus_energy[["index"]]
y = campus_energy["energy_intensity"]

model = LinearRegression()
model.fit(X, y)

campus_energy["regression_pred"] = model.predict(X)

campus_energy["smooth_pred"] = campus_energy["energy_intensity"].rolling(3).mean()

campus_energy["ensemble_pred"] = (
    campus_energy["regression_pred"]*0.5 +
    campus_energy["smooth_pred"]*0.5
)

import plotly.express as px

fig = px.bar(
    campus_energy,
    x="buildingtype",
    y="energy_intensity",
    title="Campus Energy Usage by Building Type"
)

fig.show()

